spring:

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: 123
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
        hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
    open-in-view: true
  h2:
   console:
        path: /h2
        enabled: true
